### ISSUE TITLE
Xcode 14.0.1 device_build_enabled=true fails

### ISSUE THREAD

**Issue by shahzadmajeed** [grab/cocoapods-binary-cache#113]
### Checklist

- [x ] Updated the plugin to the latest version
- [ x] I've read the [Contribution Guidelines](https://github.com/grab/cocoapods-binary-cache/blob/master/CONTRIBUTING.md)
- [x ] I've searched for [existing GitHub issues](https://github.com/grab/cocoapods-binary-cache/issues)

#### Command executed
`bundle exec pod binary prebuild --all --verbose`

#### What went wrong?
`### Error

Fails with `undefined method `map' for nil:NilClass` when enabling `device_build_enabled=true`
This setup has been working fine with Xcode 13.4.1 but fails after upgrading to Xcode 14.0.1. It works if I disable `device_build_enabled` but then I cannot build on device.

#### Stack trace

```
RuntimeError - Fail to build targets: ["AFNetworking", "FBSDKCoreKit", "FBSDKLoginKit", "FBSDKShareKit", "IQActionSheetPickerView", "MZAppearance", "MZFormSheetPresentationController", "Marshal", "PromiseKit", "SnapKit", "SwiftyAttributes", "SwiftyJSON", "JSONModel", "JSQDataSourcesKit", "LTHPasscodeViewController", "MarqueeLabel", "Rover", "UIColor-Utilities"]
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/cocoapods-binary-cache/pod-rome/xcodebuild_raw.rb:60:in `xcodebuild'
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/cocoapods-binary-cache/pod-rome/xcodebuild_command.rb:78:in `build_for_sdk'
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/cocoapods-binary-cache/pod-rome/xcodebuild_command.rb:22:in `block in run'
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/cocoapods-binary-cache/pod-rome/xcodebuild_command.rb:22:in `each'
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/cocoapods-binary-cache/pod-rome/xcodebuild_command.rb:22:in `run'
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/cocoapods-binary-cache/pod-binary/helper/build.rb:14:in `build'
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/cocoapods-binary-cache/pod-binary/prebuild.rb:53:in `prebuild_frameworks!'
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/cocoapods-binary-cache/pod-binary/prebuild.rb:163:in `block in <class:PrebuildInstaller>'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:614:in `perform_post_install_actions'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:170:in `install!'
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/cocoapods-binary-cache/hooks/pre_install.rb:102:in `block in prebuild!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:118:in `title'
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/cocoapods-binary-cache/hooks/pre_install.rb:100:in `prebuild!'
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/cocoapods-binary-cache/hooks/pre_install.rb:25:in `run'
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/cocoapods-binary-cache/pod-binary/prebuild_hook.rb:5:in `block in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/hooks_manager.rb:124:in `block (3 levels) in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:149:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/hooks_manager.rb:116:in `block (2 levels) in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/hooks_manager.rb:115:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/hooks_manager.rb:115:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:149:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/hooks_manager.rb:114:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:606:in `run_plugins_pre_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:226:in `block in prepare'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:149:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:222:in `prepare'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:160:in `install!'
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/command/executor/prebuilder.rb:31:in `block in prebuild'
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/cocoapods-binary-cache/ui.rb:5:in `block in step'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/cocoapods-binary-cache/ui.rb:5:in `step'
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/command/executor/prebuilder.rb:29:in `prebuild'
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/command/executor/prebuilder.rb:18:in `run'
/Library/Ruby/Gems/2.6.0/bundler/gems/cocoapods-binary-cache-f73781c33d07/lib/command/prebuild.rb:42:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Library/Ruby/Gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Fail+to+build+targets%3A+%5B%22AFNetworking%22%2C+%22FBSDKCoreKit%22%2C+%22FBSDKLoginKit%22%2C+%22FBSDKShareKit%22%2C+%22IQActionSheetPickerView%22%2C+%22MZAppearance%22%2C+%22MZFormSheetPresentationController%22%2C+%22Marshal%22%2C+%22PromiseKit%22%2C+%22SnapKit%22%2C+%22SwiftyAttributes%22%2C+%22SwiftyJSON%22%2C+%22JSONModel%22%2C+%22JSQDataSourcesKit%22%2C+%22LTHPasscodeViewController%22%2C+%22MarqueeLabel%22%2C+%22Rover%22%2C+%22UIColor-Utilities%22%5D&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass
```

#### Plugin version
0.1.14

#### Installed CocoaPods plugins
```
Installed CocoaPods Plugins:
    - cocoapods-binary-cache : 0.1.14 (pre_install and post_install hooks)
    - cocoapods-deintegrate  : 1.0.5
    - cocoapods-plugins      : 1.0.0
    - cocoapods-search       : 1.0.1
    - cocoapods-trunk        : 1.6.0
    - cocoapods-try          : 1.2.0
```

**Comment by shahzadmajeed** [comment]
It turns out that Facebook sdk is the problematic one. I disabled cache for that one and script is working fine now
